[book]
title = "BlueTopo"
authors = ["Glen Rice (NOAA)", "Tashi Geleg (Lynker/NOAA)"]
src = "docs"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/noaa-ocs-hydrography/BlueTopo"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["docs/theme/sidebar-logo.css"]
additional-js = ["docs/theme/sidebar-logo.js"]
